### ISSUE TITLE
P??? Avoir des données utilisateurs persistantes

### ISSUE THREAD

**Issue by ahmedahma** [SocialGouv/pass-emploi-api#10]
Ticket initié dans la branche : passemploi_database_feature

- [ ] Docker du Postgres: DONE
- [ ] Création des tables automatique au lancement du docker-compose: DONE avec l'exemple de la table Jeunes, à itérer dessus ( voir fichier sql dans la racine )
- [ ] Créer une sandbox de dev/test
- [ ] Brancher SQLALCHEMY
- [ ]  Refacto le code en intégrant la BDD ( connexion , query ... )
- [ ] Brancher alembic pour gérer les migrations
- [ ] Créer les tables côté Scalingo ( pour la prod )
- [ ] Intégrer les URL de connexion aux tables dans les variables d'env ( séparer dev de la prod )

**Comment by adgeg** [comment]
@isabelle-cerrutti : il faut juste faire une grosse passe de recette sur la nouvelle version de l'app (0.3.0 envoyée à l'instant sur Firebase) et le le nouveau site conseiller (https://pa-front-staging.osc-fr1.scalingo.io), pour vérifier que rien n'est cassé.
